# set repo for use by github-metadata
# https://github.com/mmistakes/mm-github-pages-starter/pull/2
repository: "delphidabbler/delphidabbler.github.io"

# inhibit github-pages from gerating unwanted style sheet
# see https://github.com/jekyll/jekyll/issues/7478
theme: null

exclude: [README.md, LICENSE.md, CHANGELOG.md, Gemfile, Gemfile.lock]

collections:
  applications:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: "applications"
    values:
      layout: "application-tplt"
  -
    scope:
      path: ""
    values:
      layout: "default"

