# set repo for use by github-metadata
# https://github.com/mmistakes/mm-github-pages-starter/pull/2
repository: "delphidabbler/delphidabbler.github.io"

# inhibit github-pages from gerating unwanted style sheet
# see https://github.com/jekyll/jekyll/issues/7478
theme: null

plugins:
  - jekyll-redirect-from

exclude: [README.md, LICENSE.md, Gemfile, Gemfile.lock]

collections:
  software:
    output: true
  articles:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
  -
    scope:
      path: ""
    values:
      layout: "default"

# change the following to false to re-enable flash pop-ups
ignore-flash: false

# minify CSS geerated from SASS
sass:
  style: compressed
